services:
  publisher-consumer-1: &publisher-consumer
    build:
      context: .
      dockerfile: Dockerfile.publisher-consumer
    depends_on:
      redis:
        condition: service_healthy
    container_name: rinha-publisher-consumer-1
    networks:
      - backend
      - payment-processor
    environment:
      PORT: '8080'
      PROCESSOR_DEFAULT_BASEURL: 'http://payment-processor-default:8080'
      PROCESSOR_FALLBACK_BASEURL: 'http://payment-processor-fallback:8080'
      QUEUE_BUFFER_SIZE: '20000'
      CONSUMER_GOROUTINES: '300'
      REDIS_HOST: 'rinha-redis'
      REDIS_PORT: '6379'
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '135MB'
  
  publisher-consumer-2:
    <<: *publisher-consumer
    container_name: rinha-publisher-consumer-2
    environment:
      PORT: '8080'
      PROCESSOR_DEFAULT_BASEURL: 'http://payment-processor-default:8080'
      PROCESSOR_FALLBACK_BASEURL: 'http://payment-processor-fallback:8080'
      QUEUE_BUFFER_SIZE: '20000'
      CONSUMER_GOROUTINES: '300'
      REDIS_HOST: 'rinha-redis'
      REDIS_PORT: '6379'

  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - publisher-consumer-1
      - publisher-consumer-2
    ports:
      - 9999:9999
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '20MB'

  redis:
    image: redis:7.4.5-alpine
    container_name: rinha-redis
    networks:
      - backend
    command: redis-server /etc/redis/redis.conf --save "" --appendonly no --maxclients 20000 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '60MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
